version: 2.1

orbs:
  slack: circleci/slack@4.4.4

parameters:
  param1:
    type: boolean
    default: false
  param2:
    type: boolean
    default: false

jobs:
  aks:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "Hi"
workflows:
  workflow-one:
    when: << pipeline.parameters.param1 >>
    jobs:
      - aks
  workflow-two:
    when: << pipeline.parameters.param2 >>
    jobs:
      - aks
