version: 2.1
parameters:
  reports:
    type: boolean
    default: false

jobs:
  buildone:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "From job One" >> /tmp/file1.txt
      - persist_to_workspace:
          root: /tmp/ 
          paths: 
            - file1.txt
  buildtwo:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "From job Two" >> /tmp/file2.txt
      - persist_to_workspace:
          root: /tmp/ 
          paths: 
            - file2.txt
  final:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: mkdir /tmp/reports
      - attach_workspace:
          at: /tmp/reports/
      - run: tar -cvf ob-test-reports.tar /tmp/reports
      - run: ls -ltr /tmp/reports
      - run: curl -F file=@ob-test-reports.tar -F channels=C05U7S5LNCD -H "Authorization: Bearer xoxb-5959885463845-5959897288101-0mauCaS8LFRgTnTuUV0uawvx" -H "multipart/form-data" https://slack.com/api/files.upload
      
    
workflows:
  reportsend:
    when: << pipeline.parameters.reports >>
    jobs:
      - buildone
      - buildtwo
      - final:
          requires:
            - buildone
            - buildtwo
