version: 2.1

on:
  pull_request:
    branches:
      - main    

jobs:
  aks:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: medium
    steps:
      - run: echo "Hello World!"
workflows:
  workflow-one:
    jobs:
      - aks
  workflow-two:
    jobs:
      - aks
