version: 2.1
parameters:
  first:
    type: boolean
    default: false
jobs:
  sayhello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo "Hello, World!"

workflows:
  version: 2
  say-hello-workflow:
    when:
      or:
        - << pipeline.parameters.first >>
    jobs:
      - sayhello:
          filters:
            branches:
              only:
                - main
