version: 2.1
parameters:
  first:
    type: string
    default: 1.0.1
jobs:
  sayhello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            if [ << pipeline.parameters.first >> == "1.0.*" ]; then
                echo "Hello, World!"
                echo << pipeline.parameters.first >>
            fi

workflows:
  version: 2
  say-hello-workflow:
    when:
      or:
        - << pipeline.parameters.first >>
    jobs:
      - sayhello:
          filters:
            branches:
              only:
                - main
