version: 2.1
parameters:
  reports:
    type: boolean
    default: false

jobs:
  buildone:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "From job One" >> /tmp/file1.txt
      - persist_to_workspace:
          root: /tmp/ 
          paths: 
            - file1.txt
  buildtwo:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "From job Two" >> /tmp/file2.txt
      - persist_to_workspace:
          root: /tmp/ 
          paths: 
            - file2.txt
  final:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - attach_workspace:
          at: /tmp/
      - run: pwd && ls -ltr /tmp
    
workflows:
  reportsend:
    when: << pipeline.parameters.reports >>
    jobs:
      - buildone
      - buildtwo
      - final:
          requires:
            - buildone
            - buildtwo
