version: 2.1

orbs:
  slack: circleci/slack@4.4.4

parameters:
  param1:
    type: boolean
    default: false
  param2:
    type: boolean
    default: false
  reports:
    type: boolean
    default: false

jobs:
  aks:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "Hi"
      
  buildone:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "From job One" >> /tmp/file1.txt
      - persist_to_workspace:
          root: /tmp/
    
  buildtwo:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "From job Two" >> /tmp/file2.txt
      - persist_to_workspace:
          root: /tmp/
          
  final:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - attach_workspace:
          at: /tmp/
      - run: pwd && ls -ltr
    
workflows:
  reportsend:
    when: << pipeline.parameters.reports >>
    jobs:
      - final:
          requires:
            - buildtwo
      - buildtwo:
          requires:
            - buildone
  workflow-one:
    when: << pipeline.parameters.param1 >>
    jobs:
      - aks
  workflow-two:
    when: << pipeline.parameters.param2 >>
    jobs:
      - aks
