version: 2.1

parameters:
  param1:
    type: boolean
    default: false
  param2:
    type: boolean
    default: false

jobs:
  aks:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: medium
    steps:
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts && git clone -b b1 git@github.com:vysnu96/configTest.git
workflows:
  workflow-one:
    when: << pipeline.parameters.param1 >>
    jobs:
      - aks:
          filters:
            branches:
              only:
                - main
  workflow-two:
    when: << pipeline.parameters.param2 >>
    jobs:
      - aks:
          filters:
            branches:
              only:
                - main
