version: 2.1


parameters:
  param1:
    type: boolean
    default: false
  param2:
    type: boolean
    default: false

jobs:
  aks:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: medium
    steps:
      - run: git clone -b main git@github.com:vysnu96/configTest.git && ls -ltr
workflows:
  workflow-one:
    when: << pipeline.parameters.param1 >>
    jobs:
      - aks
  workflow-two:
    when: << pipeline.parameters.param2 >>
    jobs:
      - aks
