version: 2.1

on:
  pull_request:
    branches:
      - main    

jobs:
  aks:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: medium
    steps:
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts && git clone -b b1 git@github.com:vysnu96/configTest.git
workflows:
  workflow-one:
    jobs:
      - aks
  workflow-two:
    jobs:
      - aks
