version: 2.1
parameters:
  first:
    type: boolean
    default: false
orbs:
  azure-aks: circleci/azure-aks@0.3.0
  azure-cli: circleci/azure-cli@1.2.2
  helm: circleci/helm@2.0.1
jobs:
  aks:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: medium
    steps:
      - run: sudo apt update && sudo apt install snapd && sudo snap install kubelogin
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: test
          install-kubectl: true
          perform-login: true
          resource-group: aks-new
      # - run: az aks get-credentials --format azure
      - run: az aks get-credentials --name test --overwrite-existing --resource-group aks-new --format azure
      - run: export KUBECONFIG="~/.kube/config"
      - run: kubelogin convert-kubeconfig
      - run: kubectl get services
      - helm/install-helm-client
      - run: helm upgrade my-release oci://registry-1.docker.io/bitnamicharts/nginx

workflows:
  workflow:
    when: << pipeline.parameters.first >>
    jobs:
      - aks
