version: 2.1

parameters:
  param1:
    type: boolean
    default: false
  param2:
    type: boolean
    default: false
  name:
    type: string
    default: test

jobs:
  aks:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo << pipeline.parameters.name >>
workflows:
  workflow-one:
    when: 
      or: [ << pipeline.parameters.param1 >>, << pipeline.parameters.name >> ]
    jobs:
      - aks
  workflow-two:
    when: 
      or: [ << pipeline.parameters.param2 >>, << pipeline.parameters.name >> ]
    jobs:
      - aks
