version: 2.1
parameters:
  reports:
    type: boolean
    default: false

jobs:
  buildone:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "From job One" >> /tmp/file1.txt
      - persist_to_workspace:
          root: /tmp/   
  buildtwo:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo "From job Two" >> /tmp/file2.txt
      - persist_to_workspace:
          root: /tmp/    
  final:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - attach_workspace:
          at: /tmp/
      - run: pwd && ls -ltr
    
workflows:
  reportsend:
    when: << pipeline.parameters.reports >>
    jobs:
      - final:
          requires:
            - buildone
            - buildtwo
      #     requires:
      #       - buildtwo
      # - buildtwo:
      #     requires:
      #       - buildone
      # - buildone
