version: 2.1

parameters:
  param1:
    type: boolean
    default: false
  param2:
    type: boolean
    default: false
  name:
    type: string
    default: test

jobs:
  aks:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: echo << pipeline.parameters.name >>
workflows:
  workflow-one:
    when: << pipeline.parameters.param1 >>
    jobs:
      - aks
  workflow-two:
    when: << pipeline.parameters.param2 >>
    jobs:
      - aks
