on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          token: ${{ secrets.CCI_TOKEN }}
          organization: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          branch: $GITHUB_HEAD_REF
