on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sample command
        run: |
          echo "Ref: ${{ github.ref }}"
          #echo $GITHUB_REF_NAME
          echo $GITHUB_HEAD_REF
