on:
  push:
    branches:
      - main
    # paths: ['folder1/**', 'folder2/**']
  # pull_request:
  #   types:
  #     - opened
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        run: |
          prNum=${{ GITHUB_ACTOR }}
          echo $prNum
