on:
  push:
    branches: 
      - qa
    paths: 
      - 'folder1/**'
      - 'folder2/**'

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      jobone: ${{ steps.filter.outputs.jobone }}
      jobtwo: ${{ steps.filter.outputs.jobtwo }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          jobone:
            - 'folder1/**'
          jobtwo:
            - 'folder2/**'

  dev:
    needs: changes
    if: ${{ needs.changes.outputs.jobone == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dev job
        run: |
         curl --request POST https://circleci.com/api/v2/project/gh/vysnu96/configTest/pipeline --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" --header "content-type: application/json" -d "{\"branch\":\"dev\",\"parameters\":{\"name\":\"Folder1 changed in $GITHUB_HEAD_REF\",\"param1\":true}}"

  qa:
    if: ${{ needs.changes.outputs.jobtwo == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Qa job
        run: |
         curl --request POST https://circleci.com/api/v2/project/gh/vysnu96/configTest/pipeline --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" --header "content-type: application/json" -d "{\"branch\":\"qa\",\"parameters\":{\"name\":\"Folder2 changed in $GITHUB_HEAD_REF\",\"param2\":true}}"


  # dev:
  #   if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'folder1/')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dev job
  #       run: |
  #        curl --request POST https://circleci.com/api/v2/project/gh/vysnu96/configTest/pipeline --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" --header "content-type: application/json" -d "{\"branch\":\"dev\",\"parameters\":{\"name\":\"Folder1 changed in $GITHUB_HEAD_REF\",\"param1\":true}}"

  # qa:
  #   if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'folder2/')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Qa job
  #       run: |
  #        curl --request POST https://circleci.com/api/v2/project/gh/vysnu96/configTest/pipeline --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" --header "content-type: application/json" -d "{\"branch\":\"qa\",\"parameters\":{\"name\":\"Folder2 changed in $GITHUB_HEAD_REF\",\"param2\":true}}"
