on:
  pull_request:
    types:
      - opened
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        run: |
          branch=`echo ${{ github.event.pull_request.head.ref }}`
          echo $branch
