on:
  push:
    branches: 
      - dev
    paths: 
      - 'folder1/**'
      - 'folder2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        run: |
         curl --request POST https://circleci.com/api/v2/project/gh/vysnu96/configTest/pipeline --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" --header "content-type: application/json" -d "{\"branch\":\"dev\",\"parameters\":{\"param1\":true}}"
