on:
  push:
    branches: 
      - qa
    paths: 
      - 'folder1/**'
      - 'folder2/**'

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Dev job
        run: |
         curl --request POST https://circleci.com/api/v2/project/gh/vysnu96/configTest/pipeline --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" --header "content-type: application/json" -d "{\"branch\":\"dev\",\"parameters\":{\"name\":\"Hi from Dev\",\"param1\":true}}"

  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Qa job
        run: |
         curl --request POST https://circleci.com/api/v2/project/gh/vysnu96/configTest/pipeline --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" --header "content-type: application/json" -d "{\"branch\":\"qa\",\"parameters\":{\"name\":\"Hi from Qa\",\"param2\":true}}"
